# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np
import pandas as pd

In [7]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3], [4, 5,6],[7,8,9]], [[10, 11, 12], [13,14,15],[16,17,18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [15]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape
a1.ndim
a1.dtype
a1.size
type(a1)

numpy.ndarray

In [20]:
# Attributes of 2-dimensional array
a2.shape
a2.ndim
a2.dtype
a2.size
type(a2)

numpy.ndarray

In [24]:
# Attributes of 3-dimensional array
a3.shape
a3.ndim
a3.dtype
a3.size

18

In [27]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
a2data = pd.DataFrame(a2) 


In [28]:
a2data

0  1  2
0  1  2  3
1  4  5  6

In [30]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [32]:
# Create an array of shape (7, 2, 3) of only zeros
zeroes = np.zeros((7, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [34]:
# Create an array within a range of 0 and 100 with step 3
step3 = np.arange(0, 100, 3)
step3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [38]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
ran1 = np.random.randint(0, 10, size=(7, 2))
ran1

array([[4, 4],
       [8, 5],
       [9, 2],
       [5, 1],
       [9, 6],
       [0, 4],
       [7, 2]])

In [37]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
ran2 = np.random.rand(3, 5)
ran2

array([[0.14730223, 0.68570296, 0.91828367, 0.48115565, 0.3925676 ],
       [0.46488875, 0.42722164, 0.63864165, 0.8205143 , 0.84885032],
       [0.80880439, 0.80808058, 0.67149798, 0.42365368, 0.52521043]])

In [47]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
ran3 = np.random.randint(0,10, (4,6))
print(ran3)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [50]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_number = np.random.randint(1, 10, (3, 7))

random_number

# Find the unique numbers in the array you just created


array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3],
       [1, 8, 3, 3, 1, 5, 7]])

In [51]:
np.unique(random_number)


array([1, 2, 3, 5, 7, 8, 9])

In [52]:
# Find the 0'th index of the latest array you created
random_number[0]

array([2, 5, 8, 9, 9, 1, 9])

In [53]:
# Get the first 2 rows of latest array you created
random_number[:2]

array([[2, 5, 8, 9, 9, 1, 9],
       [7, 9, 8, 1, 8, 8, 3]])

In [54]:
# Get the first 2 values of the first 2 rows of the latest array
random_number[:2, :2]

array([[2, 5],
       [7, 9]])

In [85]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array = np.random.randint(0, 10, (3, 5))
ones_array = np.ones((3, 5))    

In [65]:
random_array

array([[3, 3, 4, 6, 6],
       [3, 6, 2, 5, 1],
       [9, 8, 4, 5, 3]])

In [57]:
ones_array


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
# Add the two arrays together
random_array + ones_array

array([[ 4.,  4.,  5.,  7.,  7.],
       [ 4.,  7.,  3.,  6.,  2.],
       [10.,  9.,  5.,  6.,  4.]])

In [67]:
# Create another array of ones of shape (5, 3)
new_array = np.ones((5, 3))

In [69]:
# Try add the array of ones and the other most recent array together
new_array.T + ones_array

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [70]:
# Create another array of ones of shape (3, 5)
array35 = np.ones((3, 5))

In [71]:
# Subtract the new array of ones from the other most recent array
array35 - ones_array

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [72]:
# Multiply the ones array with the latest array
array35 * random_array

array([[3., 3., 4., 6., 6.],
       [3., 6., 2., 5., 1.],
       [9., 8., 4., 5., 3.]])

In [73]:
# Take the latest array to the power of 2 using '**'
random_array ** 2

array([[ 9,  9, 16, 36, 36],
       [ 9, 36,  4, 25,  1],
       [81, 64, 16, 25,  9]])

In [74]:
# Do the same thing with np.square()
np.square(random_array)

array([[ 9,  9, 16, 36, 36],
       [ 9, 36,  4, 25,  1],
       [81, 64, 16, 25,  9]])

In [76]:
# Find the mean of the latest array using np.mean()
np.mean(random_array)

4.533333333333333

In [77]:
# Find the maximum of the latest array using np.max()
np.max(random_array)

9

In [78]:
# Find the minimum of the latest array using np.min()
np.min(random_array)

1

In [80]:
# Find the standard deviation of the latest array
np.std(random_array)

2.124983660067897

In [81]:
# Find the variance of the latest array
np.var(random_array)

4.515555555555555

In [86]:
# Reshape the latest array to (3, 5, 1)
np.reshape(random_array, (3, 5, 1))

array([[[7],
        [6],
        [2],
        [0],
        [0]],

       [[2],
        [5],
        [6],
        [5],
        [5]],

       [[5],
        [2],
        [5],
        [7],
        [1]]])

In [87]:
# Transpose the latest array
random_array.T

array([[7, 2, 5],
       [6, 5, 2],
       [2, 6, 5],
       [0, 5, 7],
       [0, 5, 1]])

What does the transpose do?

In [90]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
ran1 = np.random.randint(0, 10, (3, 3))
ran2 = np.random.randint(0, 10, (3, 2)) 

In [92]:
ran1

array([[0, 4, 2],
       [0, 3, 4],
       [6, 0, 2]])

In [98]:
ran2

array([[1, 8],
       [9, 5],
       [9, 2]])

In [99]:
# Perform a dot product on the two newest arrays you created
np.dot(ran1, ran2)

array([[54, 24],
       [63, 23],
       [24, 52]])

In [100]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
ran3 = np.random.randint(0, 10, (4, 3))
ran4 = np.random.randint(0, 10, (4, 3))

In [101]:
ran3

array([[7, 7, 1],
       [5, 6, 1],
       [9, 1, 9],
       [0, 7, 0]])

In [102]:
ran4

array([[8, 5, 6],
       [9, 6, 9],
       [2, 1, 8],
       [7, 9, 6]])

In [104]:
# Perform a dot product on the two newest arrays you created
np.dot(ran3, ran4.T)

array([[ 97, 114,  29, 118],
       [ 76,  90,  24,  95],
       [131, 168,  91, 126],
       [ 35,  42,   7,  63]])

It doesn't work. How would you fix it?

In [39]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both


Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [105]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10, (6,7))
arr2 = np.random.randint(0, 10, (6,7))  

In [107]:
# Compare the two arrays with '>'
arr1

array([[8, 3, 3, 0, 7, 2, 6],
       [1, 1, 6, 5, 2, 8, 9],
       [5, 9, 9, 5, 0, 3, 9],
       [5, 5, 4, 0, 7, 4, 4],
       [6, 3, 5, 3, 2, 6, 7],
       [3, 1, 9, 2, 0, 7, 2]])

In [108]:
arr2

array([[9, 6, 9, 4, 9, 4, 6],
       [8, 4, 0, 9, 9, 0, 1],
       [5, 8, 7, 4, 0, 6, 4],
       [5, 6, 2, 9, 2, 4, 5],
       [8, 4, 0, 3, 4, 9, 9],
       [4, 6, 3, 0, 4, 6, 9]])

In [110]:
arr1 >= arr2

array([[False, False, False, False, False, False,  True],
       [False, False,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [ True, False,  True, False,  True,  True, False],
       [False, False,  True,  True, False, False, False],
       [False, False,  True,  True, False,  True, False]])

What happens when you compare the arrays with `>`?

In [111]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False, False, False, False, False, False,  True],
       [False, False,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True, False,  True],
       [ True, False,  True, False,  True,  True, False],
       [False, False,  True,  True, False, False, False],
       [False, False,  True,  True, False,  True, False]])

In [112]:
# Find which elements of the first array are greater than 7
arr1 > 7

array([[ True, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [False,  True,  True, False, False, False,  True],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False,  True, False, False, False, False]])

In [113]:
# Which parts of each array are equal? (try using '==')
arr1 == arr2

array([[False, False, False, False, False, False,  True],
       [False, False, False, False, False, False, False],
       [ True, False, False, False,  True, False, False],
       [ True, False, False, False, False,  True, False],
       [False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False]])

In [115]:
# Sort one of the arrays you just created in ascending order
arr1.sort()

In [116]:
arr1

array([[0, 2, 3, 3, 6, 7, 8],
       [1, 1, 2, 5, 6, 8, 9],
       [0, 3, 5, 5, 9, 9, 9],
       [0, 4, 4, 4, 5, 5, 7],
       [2, 3, 3, 5, 6, 6, 7],
       [0, 1, 2, 2, 3, 7, 9]])

In [117]:
# Sort the indexes of one of the arrays you just created
arr1.argsort()


array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]])

In [118]:
arr1

array([[0, 2, 3, 3, 6, 7, 8],
       [1, 1, 2, 5, 6, 8, 9],
       [0, 3, 5, 5, 9, 9, 9],
       [0, 4, 4, 4, 5, 5, 7],
       [2, 3, 3, 5, 6, 6, 7],
       [0, 1, 2, 2, 3, 7, 9]])

In [120]:
# Find the index with the maximum value in one of the arrays you've created
arr1.max()

9

In [121]:
# Find the index with the minimum value in one of the arrays you've created
arr1.min()

0

In [125]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
arr1.argmax(axis=1)

array([6, 6, 4, 6, 6, 6])

In [126]:
np.argmax(arr1, axis=1)

array([6, 6, 4, 6, 6, 6])

In [127]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
arr2.argmax(axis=0)

array([0, 2, 0, 1, 0, 4, 4])

In [135]:
# Create an array of normally distributed random numbers
ran_array = np.random.randn(3,5)

In [136]:
ran_array

array([[ 1.44127329, -1.43586215,  1.16316375,  0.01023306, -0.98150865],
       [ 0.46210347,  0.1990597 , -0.60021688,  0.06980208, -0.3853136 ],
       [ 0.11351735,  0.66213067,  1.58601682, -1.2378155 ,  2.13303337]])

In [142]:
# Create an array with 10 evenly spaced numbers between 1 and 100
tensarray = np.linspace(1, 100, 10
                        )

In [143]:
tensarray

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.