In [202]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn

Datatype and attributes
numpy main datatypes is ndarray

In [203]:
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [204]:
type(a1)

numpy.ndarray

In [205]:
a2= np.array([[1,2,3.3], [4,5,6.6]])
a3 = np.array([[[1,2,3], 
               [4,5,6], 
               [7,8,9]], 
               [[10,11,12], 
               [13,14,15], 
               [16,17,18 ]]]) 

In [206]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [207]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [208]:
a1.shape
a2.shape
a3.shape



(2, 3, 3)

In [209]:
a1.ndim, a3.ndim

(1, 3)

In [210]:
a2.dtype

dtype('float64')

In [211]:
a3.dtype

dtype('int64')

In [212]:
a3.size

18

In [213]:
type(a2)

numpy.ndarray

In [214]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

In [215]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [216]:
sample_array.dtype

dtype('int64')

In [217]:
ones = np.ones(3)                           

In [218]:
ones.dtype
type(ones)

numpy.ndarray

In [219]:
zeros = np.zeros((2,3))


In [220]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [221]:
range_array = np.arange(0, 10 , 2)
range_array

array([0, 2, 4, 6, 8])

In [222]:
random_array = np.random.randint(0,10, size=(3,5))
random_array

array([[0, 5, 3, 0, 5],
       [7, 1, 8, 4, 9],
       [0, 2, 0, 7, 6]])

In [223]:
random_array.size

15

In [224]:
random_array.shape


(3, 5)

In [225]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.55054305, 0.52259111, 0.48755248],
       [0.26303148, 0.52728579, 0.98446573],
       [0.62342345, 0.62955693, 0.9099729 ],
       [0.96251949, 0.5850998 , 0.16489774],
       [0.39159332, 0.94455493, 0.34339118]])

In [226]:
random_array_2.shape

(5, 3)

In [227]:
random_array_3 = np.random.rand(5, 3)
random_array_3


array([[0.70507037, 0.4628868 , 0.38679069],
       [0.52843256, 0.82168992, 0.63847702],
       [0.86288872, 0.63662654, 0.99929706],
       [0.51778008, 0.32761664, 0.09877324],
       [0.5667664 , 0.21520794, 0.01179079]])

In [228]:
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size = (5,3))


In [229]:
random_array_4 


array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [230]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))

In [231]:
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

3. Viewing arrays and matrices


In [232]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [233]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.6]]))

In [234]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [235]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [236]:
a2[0]

array([1. , 2. , 3.3])

In [237]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [238]:
a2[1]

array([4. , 5. , 6.6])

In [239]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [240]:
a4 = np.random.randint(10, size = (2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [241]:
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

4. manipulating and comparing arrays


In [242]:
a1


array([1, 2, 3])

In [243]:
ones=np.ones(3)


In [244]:
ones

array([1., 1., 1.])

In [245]:
a1 + ones

array([2., 3., 4.])

In [246]:
a1 - ones

array([0., 1., 2.])

In [247]:
a1 * 1

array([1, 2, 3])

In [248]:
a2 

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [249]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.8]])

In [250]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a2.reshape((2,3,1))

In [ ]:
a2.reshape((2,3))

In [ ]:
a2//a1

In [ ]:
a2 ** 2

In [ ]:
a2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
a1 / 2

In [ ]:
listy_list = [1,2,3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
np.sum(a1)

In [ ]:
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:20]

In [ ]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

In [ ]:
np.mean(a2)

In [ ]:
a2

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
np.std(a2)

In [ ]:
np.mean(a2)

In [ ]:
np.var(a2)

In [ ]:
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array) , np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
plt.hist(high_var_array)
plt.show()


In [ ]:
plt.hist(low_var_array)
plt.show()


In [ ]:
# reshaping and transposing


In [251]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2.reshape(2,3,1)

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a2_reshape * a3

In [ ]:
a2.T

In [ ]:
a2.T.shape

In [ ]:
a3.shape

In [ ]:
a3.T.shape

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size = (5,3 ))
mat2 = np.random.randint(10, size = (5,3 ))

mat1 


In [ ]:
mat2.T

In [ ]:
mat1 * mat2

In [ ]:
mat3 = np.dot(mat1, mat2.T)

In [ ]:
mat3

In [ ]:
mat4 = np.dot(mat1.T, mat2)

In [ ]:
mat4

In [ ]:
# dot product example


In [254]:
np.random.seed(0)
sales_amount = np.random.randint(20, size = (5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [255]:
weekly_sales = pd.DataFrame(sales_amount, index = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri'], columns = ['Almond butter', 'Peanut butter' , 'Cashew butter'])

In [256]:
weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [257]:
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [258]:
butter_prices = pd.DataFrame(prices.reshape(1,3), index=['Price'], columns = ['Almond butter', 'Peanut butter' , 'Cashew butter'])

In [259]:
sales_amount.shape

(5, 3)

In [260]:
total_sales = prices.dot(sales_amount.T)

In [261]:
total_sales

array([240, 138, 458, 232, 142])

In [262]:
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [263]:
butter_prices.shape, weekly_sales.shape

((1, 3), (5, 3))

In [264]:
daily_sales = butter_prices.dot(weekly_sales.T)

In [265]:
daily_sales

Mon  Tue  Wed  Thu  Fri
Price  240  138  458  232  142

In [267]:
weekly_sales['Total ($)'] = daily_sales.T

In [268]:
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142

In [269]:
a1, a2

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.6]]))

In [274]:
bool_array = a1>=a2
bool_array

array([[ True,  True, False],
       [False, False, False]])

In [275]:
type(bool_array), bool_array.dtype

(numpy.ndarray, dtype('bool'))

In [276]:
a1 >1

array([False,  True,  True])

In [278]:
a1 == a1

array([ True,  True,  True])

In [280]:
random_array = np.random.randint(10,size = (3,5))

In [283]:
random_array, random_array.shape

(array([[7, 8, 1, 5, 9],
        [8, 9, 4, 3, 0],
        [3, 5, 0, 2, 3]]),
 (3, 5))

In [285]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [287]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [288]:
a1


array([1, 2, 3])

In [289]:
np.argsort(a1)

array([0, 1, 2])

In [290]:
np.argmin(a1), np.argmax(a1)

(0, 2)

In [291]:
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [295]:
np.argmax(random_array, axis=1)

array([4, 1, 1])

In [296]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [303]:
from matplotlib.image import imread

panda = imread("numpy-panda.png")
car = imread("numpy-car-photo.png")
dog = imread("numpy-dog-photo.png")
print(type(panda))

<class 'numpy.ndarray'>


In [301]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [304]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [305]:
type(car)

numpy.ndarray